# Generated by Django 4.2.11 on 2025-11-29 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('BREACHED', 'Breached'), ('EXCEEDED', 'Exceeded')], default='ON_TRACK', max_length=20)),
            ],
        ),
    ]
