apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app-2
  template:
    metadata:
      labels:
        app: django-app-2
    spec:
      containers:
      - name: django
        image: hinn8823/devnet_dashboard:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
