# Generated by Django 4.2.11 on 2025-11-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='operation',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
